sonar.projectKey=HotfixInProduction_hotfixinprod
sonar.organization=hotfixinproduction

# Path to source directories
sonar.sources=src
sonar.tests=__tests__

# Exclude coverage files and test files
sonar.exclusions=**/*.test.tsx,**/*.test.ts,**/coverage/**,**/node_modules/**,**/android/**,**/ios/**,**/__mocks__/**,**/package-lock.json,**/*.config.js,**/build/**,**/.expo/**,**/.expo-shared/**,**/assets/**,**/*.json

# Path to coverage reports
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# TypeScript configuration
sonar.typescript.file.suffixes=.ts,.tsx
