sonar.projectKey=your-org_hotfixinprod
sonar.organization=your-org

# Path to source directories
sonar.sources=src
sonar.tests=__tests__

# Exclude coverage files and test files
sonar.exclusions=**/*.test.tsx,**/*.test.ts,**/coverage/**,**/node_modules/**,**/android/**,**/ios/**,**/__mocks__/**,**/package-lock.json,**/yarn.lock,**/pnpm-lock.yaml

# Path to coverage reports
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# TypeScript configuration
sonar.typescript.file.suffixes=.ts,.tsx
