name: Spike
description: Research task to reduce uncertainty
title: "[SPIKE] "
labels: ["spike"]
body:
  - type: textarea
    id: goal
    attributes:
      label: Goal
    validations:
      required: true
  - type: textarea
    id: outcome
    attributes:
      label: Expected outcome
      placeholder: "Decision + pros/cons + recommended approach"
    validations:
      required: true